# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "jid-${version}";
  version = "0.6.1";
  rev = "0.6.1";

  goPackagePath = "github.com/simeji/jid";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/simeji/jid";
    sha256 = "12yyn9jk27mzc7rz16yr9yparw1xyds4gji76k36ilwyjkf4yvn4";
  };

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
    description = "Incremental JSON digger";
    license = licenses.mit;
    maintainers = [ profpatsch ];
  };
}
